apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
  labels:
    app: demo
    service: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
      service: nodeapp
  template:
    metadata:
      labels:
        app: demo
        service: nodeapp
    spec:
      containers:
      - image: bargenson/dockerdemo_nodeapp
        name: nodeapp
        ports:
        - containerPort: 8080
        env:
        - name: DEBUG
          value: "true"
        - name: PORT
          value: "8080"
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"

---

apiVersion: v1
kind: Service
metadata:
  name: nodeapp
spec:
  selector:
    app: demo
    service: nodeapp
  ports:
  - port: 8080
