apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: demo
    service: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
      service: redis
  template:
    metadata:
      labels:
        app: demo
        service: redis
    spec:
      containers:
      - image: redis:3.0
        name: redis
        ports:
        - containerPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: demo
    service: redis
  ports:
  - port: 6379
