apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: demo
    service: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
      service: web
  template:
    metadata:
      labels:
        app: demo
        service: web
    spec:
      containers:
      - image: bargenson/dockerdemo_web
        name: web
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: NodePort
  selector:
    app: demo
    service: web
  ports:
  - name: http
    port: 80
    nodePort: 32767
